In [1]:
from Data import *
import numpy as np
import pandas as pd
import re
import spacy


In [4]:
coll=Database('kxZgDBEwIHkoo9Jd').get_collection('carn')

In [30]:
coll.find({'idx':{'$lt':22}})[0]   

{'_id': ObjectId('6350690bcb07d30fb9f076c0'),
 'idx': 1,
 'title': 'experimental investigation of the aerodynamics of awing in a slipstream .',
 'author': 'brenckman,m.',
 'bib': 'j. ae. scs. 25, 1958, 324.',
 'text': 'experimental investigation of the aerodynamics of awing in a slipstream .  an experimental study of a wing in a propeller slipstream wasmade in order to determine the spanwise distribution of the liftincrease due to slipstream at different angles of attack of the wingand at different free stream to slipstream velocity ratios .  theresults were intended in part as an evaluation basis for differenttheoretical treatments of this problem .  the comparative span loading curves, together withsupporting evidence, showed that a substantial part of the lift incrementproduced by the slipstream was due to a /destalling/ orboundary-layer-control effect .  the integrated remaining liftincrement, after subtracting this destalling lift, was found to agreewell with a potential flow theo

In [85]:
from autocorrect import Speller

spell = Speller(lang='en')

In [16]:
corpus=CranCorpus("C:/Users/pc/Documents/programming/RI_TP/Datasets/Cran/cran.all.1400")
indexer=Indexer(corpus)

found empty document at index  471
found empty document at index  995


In [17]:
#indexer=Indexer(file_name='indexer01.pkl')
indexer.save('indexer01.pkl')

In [18]:
query_corpus=CranQueryCorpus("C:/Users/pc/Documents/programming/RI_TP/Datasets/Cran/cran.qry")

In [93]:
spell('caaar')

'car'

In [88]:
spell(query_corpus[4]['text'])

'what chemical kinetic system is applicable to hyperbolic aerodynamicproblems .'

In [82]:
def get_documents_for_query(query):
    similaritys=indexer.get_docs_with_jaccard_01(query)
    similaritys_idx=np.flip(np.argsort(similaritys))
    res=similaritys_idx[similaritys[similaritys_idx]>0.05]
    print("Query :",query)
    for idx in res:
        print('     ',corpus[idx]['idx'],': ',corpus[idx]['title'])


In [83]:
get_documents_for_query(query_corpus[4]['text'])

Query : what chemical kinetic system is applicable to hypersonic aerodynamicproblems .
      103 :  theory of mixing and chemical reaction in the opposedjet diffusion flame .
      1032 :  on the conservativeness of various distributed force systems .
      401 :  inviscid hypersonic airflows with coupled non-equilibriumprocesses .
      943 :  compressible free shear layer with finite initial thickness .
      552 :  chemical kinetics of high temperature air .
      367 :  control system and analysis and design via the second method oflyapunov .
      1102 :  a five-stage solid fuel sounding rocket system .
      1374 :  theoretical analysis of turbulent mixing of reactivegases with application to supersonic combustion ofhydrogen .
      968 :  rocket propulsion systems for interplanetary flight .


In [55]:
similaritys[np.flip(np.argsort(similaritys))[:10]]

array([0.45253475, 0.28494945, 0.19666849, 0.18937192, 0.17349339,
       0.17320177, 0.16350901, 0.15664807, 0.06246709, 0.06060188])

In [27]:
np.flip(np.sort(similaritys))

array([0.12139688, 0.11196342, 0.10301708, ..., 0.        , 0.        ,
       0.        ])

In [60]:
(indexer.index(query_corpus[0]['text'],binary=False)**2).sum()

1.2168591867434255

In [13]:
q=indexer.index(query_corpus[0]['text'],binary=False)

c=np.repeat([q],indexer.get_tf_idf().shape[0],axis=0)*indexer.get_tf_idf()

In [17]:
np.count_nonzero(c==np.nan)

0

In [13]:
(indexer.term_frequencys / indexer.words_in_doc[:,None]) * np.log(indexer.term_frequencys.shape[0] / indexer.nb_docs_with_word)

AttributeError: 'Indexer' object has no attribute 'words_in_doc'

In [14]:
np.count_nonzero(np.isnan((indexer.term_frequencys / indexer.words_in_doc[:,None])))

AttributeError: 'Indexer' object has no attribute 'words_in_doc'

In [40]:
np.where(indexer.words_in_doc==0)

(array([470, 994], dtype=int64),)

In [43]:
corpus[994]

{'idx': 995, 'title': '', 'author': '', 'bib': '', 'text': ''}