In [1]:
from Data import *
import numpy as np
import pandas as pd
import re
import spacy
from nltk.stem.snowball import SnowballStemmer
from nltk.stem.porter import *


In [58]:
en_mod=spacy.load('en_core_web_sm')
stemmer = SnowballStemmer(language='english')   

text='was uuunfavourable tests far fan'
[stemmer.stem(word.lemma_)  for word in en_mod(text) if not word.is_punct and not word.is_stop and not word.is_space and not word.is_digit]


['uuunfavour', 'test', 'far', 'fan']

In [33]:
coll=Database('kxZgDBEwIHkoo9Jd')

In [30]:
coll.find({'idx':{'$lt':22}})[0]   

{'_id': ObjectId('6350690bcb07d30fb9f076c0'),
 'idx': 1,
 'title': 'experimental investigation of the aerodynamics of awing in a slipstream .',
 'author': 'brenckman,m.',
 'bib': 'j. ae. scs. 25, 1958, 324.',
 'text': 'experimental investigation of the aerodynamics of awing in a slipstream .  an experimental study of a wing in a propeller slipstream wasmade in order to determine the spanwise distribution of the liftincrease due to slipstream at different angles of attack of the wingand at different free stream to slipstream velocity ratios .  theresults were intended in part as an evaluation basis for differenttheoretical treatments of this problem .  the comparative span loading curves, together withsupporting evidence, showed that a substantial part of the lift incrementproduced by the slipstream was due to a /destalling/ orboundary-layer-control effect .  the integrated remaining liftincrement, after subtracting this destalling lift, was found to agreewell with a potential flow theo

In [85]:
from autocorrect import Speller

spell = Speller(lang='en')

In [2]:
corpus=CranCorpus("C:/Users/pc/Documents/programming/RI_TP/Datasets/Cran/cran.all.1400")


In [65]:
corpus.documents

[{'idx': 1,
  'title': 'experimental investigation of the aerodynamics of awing in a slipstream .',
  'author': 'brenckman,m.',
  'bib': 'j. ae. scs. 25, 1958, 324.',
  'text': ' experimental investigation of the aerodynamics of a wing in a slipstream .   an experimental study of a wing in a propeller slipstream was made in order to determine the spanwise distribution of the lift increase due to slipstream at different angles of attack of the wing and at different free stream to slipstream velocity ratios .  the results were intended in part as an evaluation basis for different theoretical treatments of this problem .   the comparative span loading curves, together with supporting evidence, showed that a substantial part of the lift increment produced by the slipstream was due to a /destalling/ or boundary-layer-control effect .  the integrated remaining lift increment, after subtracting this destalling lift, was found to agree well with a potential flow theory .   an empirical evaluat

In [66]:
coll.Insert_Corpus(corpus)

In [4]:
indexer=Indexer(corpus)

c:\Users\pc\Documents\programming\RI_TP\Implementation\Data\Indexer.py:81: RuntimeWarning: invalid value encountered in true_divide
  return (self.term_frequencys / words_in_doc[:,None]) * np.log(self.term_frequencys.shape[0] / nb_docs_with_word)


In [5]:
file=open("terms.txt",'w')
file.write('\n'.join(indexer.terms))
file.close()

In [43]:
#indexer=Indexer(file_name='indexer01.pkl')
indexer.save('indexer01.pkl')

In [7]:
query_corpus=CranQueryCorpus("C:/Users/pc/Documents/programming/RI_TP/Datasets/Cran/cran.qry")

In [67]:
query_corpus[0]['text']

' what similarity laws must be obeyed when constructing aeroelastic models of heated high speed aircraft . '

In [108]:
idx=indexer.get_documents_for_query(query_corpus[0]['text'])
res=coll.get_collection('carn').find({'_id':{"$in":idx.tolist()}})

In [109]:
res=list(res)

In [111]:
[list(filter(lambda x:x['_id']==i,res))[0]   for i in idx]

[{'_id': 50,
  'idx': 51,
  'title': 'theory of aircraft structural models subjected to aerodynamicheating and external loads .',
  'author': "o'sullivan,w.j.",
  'bib': 'naca tn.4115, 1957.',
  'text': ' theory of aircraft structural models subjected to aerodynamic heating and external loads .   the problem of investigating the simultaneous effects of transient aerodynamic heating and external loads on aircraft structures for the purpose of determining the ability of the structure to withstand flight to supersonic speeds is studied .  by dimensional analyses it is shown that .. constructed of the same materials as the aircraft will be thermally similar to the aircraft with respect to the flow of heat through the structure will be similar to those of the aircraft when the structural model is constructed at the same temperature as the aircraft . external loads will be similar to those of the aircraft . subjected to heating and cooling that correctly simulate the aerodynamic heating of t

In [92]:
[(r['_id'],r['idx']) for r in res]

[(11, 12),
 (12, 13),
 (50, 51),
 (55, 56),
 (140, 141),
 (183, 184),
 (252, 253),
 (331, 332),
 (358, 359),
 (434, 435),
 (485, 486),
 (572, 573),
 (664, 665),
 (745, 746),
 (816, 817),
 (817, 818),
 (873, 874),
 (874, 875),
 (877, 878),
 (878, 879),
 (943, 944),
 (1168, 1169),
 (1185, 1186)]

In [70]:
idx.tolist()

[50,
 183,
 11,
 358,
 55,
 745,
 943,
 878,
 877,
 12,
 485,
 664,
 873,
 816,
 572,
 1185,
 874,
 252,
 140,
 434,
 1168,
 817,
 331]

In [ ]:
list(res)

In [22]:
query_corpus[0]['text']

' what similarity laws must be obeyed when constructing aeroelastic models of heated high speed aircraft . '

In [57]:
indx=idx.tolist()


183

In [58]:
list(coll.get_collection('carn').find({'idx':{"$in":indx}}))

[{'_id': ObjectId('6377619eec16665f07c07add'),
  'idx': 11,
  'title': 'similar solutions in compressible laminar free mixingproblems .',
  'author': 'napolitano,l.',
  'bib': 'j. ae. scs. 23, 1956, 389.',
  'text': ' similar solutions in compressible laminar free mixing problems . there are in supersonic aerodynamics many situations of practical interest wherein streams of different velocities and, in general, different stagnation pressures mix with one another . in the majority of these problems the interaction between the two streams takes place in the presence of an axial pressure gradient .  its effect on the characteristics of the mixing may influence significantly the performances of the devices wherein the phenomena cited above occur .  a theoretical and experimental program of research to study mixing in the presence of axial pressure gradients is being carried on at the polytechnic institute of brooklyn . '},
 {'_id': ObjectId('6377619eec16665f07c07ade'),
  'idx': 12,
  'titl

In [59]:
idx

array([  50,  183,   11,  358,   55,  745,  943,  878,  877,   12,  485,
        664,  873,  816,  572, 1185,  874,  252,  140,  434, 1168,  817,
        331], dtype=int64)

In [44]:
corpus[idx[1]]

{'idx': 184,
 'title': 'scale models for thermo-aeroelastic research .',
 'author': 'molyneux,w.g.',
 'bib': 'rae tn.struct.294, 1961.',
 'text': ' scale models for thermo-aeroelastic research .   an investigation is made of the parameters to be satisfied for thermo-aeroelastic similarity .  it is concluded that complete similarity obtains only when aircraft and model are identical in all respects, including size .   by limiting consideration to conduction effects, by assuming the major load carrying parts of the structure are in regions where the flow is either entirely laminar, or entirely turbulent, and by assuming a specific relationship between reynolds number and nusselt number, an approach to similarity can be achieved for small scale models . experimental and analytical work is required to check on the validity of these assumptions .   it appears that existing hot wind tunnels will not be completely adequate for thermo-aeroelastic work, and accordingly a possible layout for the

In [4]:
def get_documents_for_query(query):
    similaritys=indexer.get_docs_with_jaccard_01(query)
    similaritys_idx=np.flip(np.argsort(similaritys))
    res=similaritys_idx[similaritys[similaritys_idx]>0.05]
    print("Query :",query)
    for idx in res:
        print('     ',corpus[idx]['idx'],': ',corpus[idx]['title'])


In [7]:
get_documents_for_query(query_corpus[4]['text'])

Query : what chemical kinetic system is applicable to hypersonic aerodynamicproblems .
      103 :  theory of mixing and chemical reaction in the opposedjet diffusion flame .
      1032 :  on the conservativeness of various distributed force systems .
      401 :  inviscid hypersonic airflows with coupled non-equilibriumprocesses .
      943 :  compressible free shear layer with finite initial thickness .
      552 :  chemical kinetics of high temperature air .
      367 :  control system and analysis and design via the second method oflyapunov .
      1102 :  a five-stage solid fuel sounding rocket system .
      1374 :  theoretical analysis of turbulent mixing of reactivegases with application to supersonic combustion ofhydrogen .
      968 :  rocket propulsion systems for interplanetary flight .


In [55]:
similaritys[np.flip(np.argsort(similaritys))[:10]]

array([0.45253475, 0.28494945, 0.19666849, 0.18937192, 0.17349339,
       0.17320177, 0.16350901, 0.15664807, 0.06246709, 0.06060188])

In [27]:
np.flip(np.sort(similaritys))

array([0.12139688, 0.11196342, 0.10301708, ..., 0.        , 0.        ,
       0.        ])

In [60]:
(indexer.index(query_corpus[0]['text'],binary=False)**2).sum()

1.2168591867434255

In [13]:
q=indexer.index(query_corpus[0]['text'],binary=False)

c=np.repeat([q],indexer.get_tf_idf().shape[0],axis=0)*indexer.get_tf_idf()

In [17]:
np.count_nonzero(c==np.nan)

0

In [13]:
(indexer.term_frequencys / indexer.words_in_doc[:,None]) * np.log(indexer.term_frequencys.shape[0] / indexer.nb_docs_with_word)

AttributeError: 'Indexer' object has no attribute 'words_in_doc'

In [14]:
np.count_nonzero(np.isnan((indexer.term_frequencys / indexer.words_in_doc[:,None])))

AttributeError: 'Indexer' object has no attribute 'words_in_doc'

In [40]:
np.where(indexer.words_in_doc==0)

(array([470, 994], dtype=int64),)

In [43]:
corpus[994]

{'idx': 995, 'title': '', 'author': '', 'bib': '', 'text': ''}